[template]
src = "mongodb_exporter.sh.tmpl"
dest = "/opt/app/current/bin/tmpl/mongodb_exporter.sh"
mode = "0700"
keys = [
    "/",
]
reload_cmd = "/opt/app/current/bin/tmpl/mongodb_exporter.sh; appctl reloadMongoDBExporter"